/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name The name of the new runner.
 * @param runnerGroupId The ID of the runner group to register the runner to.
 * @param labels The names of the custom labels to add to the runner. **Minimum items**: 1. **Maximum items**: 100.
 * @param workFolder The working directory to be used for job execution, relative to the runner install directory.
 */
@Serializable

data class ActionsGenerateRunnerJitconfigForOrgRequest (

    /* The name of the new runner. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The ID of the runner group to register the runner to. */
    @SerialName(value = "runner_group_id")
    val runnerGroupId: kotlin.Int,

    /* The names of the custom labels to add to the runner. **Minimum items**: 1. **Maximum items**: 100. */
    @SerialName(value = "labels")
    val labels: kotlin.collections.List<kotlin.String>,

    /* The working directory to be used for job execution, relative to the runner install directory. */
    @SerialName(value = "work_folder")
    val workFolder: kotlin.String? = "_work"

)

