/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Repository

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param totalCount 
 * @param repositories 
 */
@Serializable

data class ActionsListSelectedRepositoriesEnabledGithubActionsOrganization200Response (

    @Contextual @SerialName(value = "total_count")
    val totalCount: java.math.BigDecimal,

    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<Repository>

)

