/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ignored Whether to block all notifications from a thread.
 */
@Serializable

data class ActivitySetThreadSubscriptionRequest (

    /* Whether to block all notifications from a thread. */
    @SerialName(value = "ignored")
    val ignored: kotlin.Boolean? = false

)

