/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Job

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param totalCount 
 * @param jobs 
 */
@Serializable

data class ActionsListJobsForWorkflowRunAttempt200Response (

    @SerialName(value = "total_count")
    val totalCount: kotlin.Int,

    @SerialName(value = "jobs")
    val jobs: kotlin.collections.List<Job>

)

