/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Actor
 *
 * @param id 
 * @param login 
 * @param gravatarId 
 * @param url 
 * @param avatarUrl 
 * @param displayLogin 
 */
@Serializable

data class Actor (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "login")
    val login: kotlin.String,

    @SerialName(value = "gravatar_id")
    val gravatarId: kotlin.String?,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @Contextual @SerialName(value = "avatar_url")
    val avatarUrl: java.net.URI,

    @SerialName(value = "display_login")
    val displayLogin: kotlin.String? = null

)

