/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ApiOverviewDomains
import org.openapitools.client.models.ApiOverviewSshKeyFingerprints

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Api Overview
 *
 * @param verifiablePasswordAuthentication 
 * @param sshKeyFingerprints 
 * @param sshKeys 
 * @param hooks 
 * @param githubEnterpriseImporter 
 * @param web 
 * @param api 
 * @param git 
 * @param packages 
 * @param pages 
 * @param importer 
 * @param actions 
 * @param dependabot 
 * @param domains 
 */
@Serializable

data class ApiOverview (

    @SerialName(value = "verifiable_password_authentication")
    val verifiablePasswordAuthentication: kotlin.Boolean,

    @SerialName(value = "ssh_key_fingerprints")
    val sshKeyFingerprints: ApiOverviewSshKeyFingerprints? = null,

    @SerialName(value = "ssh_keys")
    val sshKeys: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "hooks")
    val hooks: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "github_enterprise_importer")
    val githubEnterpriseImporter: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "web")
    val web: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "api")
    val api: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "git")
    val git: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "packages")
    val packages: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "pages")
    val pages: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "importer")
    val importer: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "actions")
    val actions: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "dependabot")
    val dependabot: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "domains")
    val domains: ApiOverviewDomains? = null

)

