/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AppPermissions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param repositories List of repository names that the token should have access to
 * @param repositoryIds List of repository IDs that the token should have access to
 * @param permissions 
 */
@Serializable

data class AppsCreateInstallationAccessTokenRequest (

    /* List of repository names that the token should have access to */
    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<kotlin.String>? = null,

    /* List of repository IDs that the token should have access to */
    @SerialName(value = "repository_ids")
    val repositoryIds: kotlin.collections.List<kotlin.Int>? = null,

    @SerialName(value = "permissions")
    val permissions: AppPermissions? = null

)

