/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SimpleUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The status of auto merging a pull request.
 *
 * @param enabledBy 
 * @param mergeMethod The merge method to use.
 * @param commitTitle Title for the merge commit message.
 * @param commitMessage Commit message for the merge commit.
 */
@Serializable

data class AutoMerge (

    @SerialName(value = "enabled_by")
    val enabledBy: SimpleUser,

    /* The merge method to use. */
    @SerialName(value = "merge_method")
    val mergeMethod: AutoMerge.MergeMethod,

    /* Title for the merge commit message. */
    @SerialName(value = "commit_title")
    val commitTitle: kotlin.String,

    /* Commit message for the merge commit. */
    @SerialName(value = "commit_message")
    val commitMessage: kotlin.String

) {

    /**
     * The merge method to use.
     *
     * Values: merge,squash,rebase
     */
    @Serializable
    enum class MergeMethod(val value: kotlin.String) {
        @SerialName(value = "merge") merge("merge"),
        @SerialName(value = "squash") squash("squash"),
        @SerialName(value = "rebase") rebase("rebase");
    }
}

