/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BranchProtectionAllowForkSyncing
import org.openapitools.client.models.BranchProtectionLockBranch
import org.openapitools.client.models.BranchProtectionRequiredLinearHistory
import org.openapitools.client.models.BranchProtectionRequiredSignatures
import org.openapitools.client.models.BranchRestrictionPolicy
import org.openapitools.client.models.ProtectedBranchAdminEnforced
import org.openapitools.client.models.ProtectedBranchPullRequestReview
import org.openapitools.client.models.ProtectedBranchRequiredStatusCheck

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Branch Protection
 *
 * @param url 
 * @param enabled 
 * @param requiredStatusChecks 
 * @param enforceAdmins 
 * @param requiredPullRequestReviews 
 * @param restrictions 
 * @param requiredLinearHistory 
 * @param allowForcePushes 
 * @param allowDeletions 
 * @param blockCreations 
 * @param requiredConversationResolution 
 * @param name 
 * @param protectionUrl 
 * @param requiredSignatures 
 * @param lockBranch 
 * @param allowForkSyncing 
 */
@Serializable

data class BranchProtection (

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null,

    @SerialName(value = "required_status_checks")
    val requiredStatusChecks: ProtectedBranchRequiredStatusCheck? = null,

    @SerialName(value = "enforce_admins")
    val enforceAdmins: ProtectedBranchAdminEnforced? = null,

    @SerialName(value = "required_pull_request_reviews")
    val requiredPullRequestReviews: ProtectedBranchPullRequestReview? = null,

    @SerialName(value = "restrictions")
    val restrictions: BranchRestrictionPolicy? = null,

    @SerialName(value = "required_linear_history")
    val requiredLinearHistory: BranchProtectionRequiredLinearHistory? = null,

    @SerialName(value = "allow_force_pushes")
    val allowForcePushes: BranchProtectionRequiredLinearHistory? = null,

    @SerialName(value = "allow_deletions")
    val allowDeletions: BranchProtectionRequiredLinearHistory? = null,

    @SerialName(value = "block_creations")
    val blockCreations: BranchProtectionRequiredLinearHistory? = null,

    @SerialName(value = "required_conversation_resolution")
    val requiredConversationResolution: BranchProtectionRequiredLinearHistory? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "protection_url")
    val protectionUrl: kotlin.String? = null,

    @SerialName(value = "required_signatures")
    val requiredSignatures: BranchProtectionRequiredSignatures? = null,

    @SerialName(value = "lock_branch")
    val lockBranch: BranchProtectionLockBranch? = null,

    @SerialName(value = "allow_fork_syncing")
    val allowForkSyncing: BranchProtectionAllowForkSyncing? = null

)

