/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CheckRunCheckSuite
import org.openapitools.client.models.CheckRunOutput
import org.openapitools.client.models.DeploymentSimple
import org.openapitools.client.models.IssuePerformedViaGithubApp
import org.openapitools.client.models.PullRequestMinimal

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A check performed on the code of a given code change
 *
 * @param id The id of the check.
 * @param headSha The SHA of the commit that is being checked.
 * @param nodeId 
 * @param externalId 
 * @param url 
 * @param htmlUrl 
 * @param detailsUrl 
 * @param status The phase of the lifecycle that the check is currently in. Statuses of waiting, requested, and pending are reserved for GitHub Actions check runs.
 * @param conclusion 
 * @param startedAt 
 * @param completedAt 
 * @param output 
 * @param name The name of the check.
 * @param checkSuite 
 * @param app 
 * @param pullRequests Pull requests that are open with a `head_sha` or `head_branch` that matches the check. The returned pull requests do not necessarily indicate pull requests that triggered the check.
 * @param deployment 
 */
@Serializable

data class CheckRun (

    /* The id of the check. */
    @SerialName(value = "id")
    val id: kotlin.Int,

    /* The SHA of the commit that is being checked. */
    @SerialName(value = "head_sha")
    val headSha: kotlin.String,

    @SerialName(value = "node_id")
    val nodeId: kotlin.String,

    @SerialName(value = "external_id")
    val externalId: kotlin.String?,

    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String?,

    @SerialName(value = "details_url")
    val detailsUrl: kotlin.String?,

    /* The phase of the lifecycle that the check is currently in. Statuses of waiting, requested, and pending are reserved for GitHub Actions check runs. */
    @SerialName(value = "status")
    val status: CheckRun.Status,

    @SerialName(value = "conclusion")
    val conclusion: CheckRun.Conclusion?,

    @Contextual @SerialName(value = "started_at")
    val startedAt: kotlinx.datetime.Instant?,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "output")
    val output: CheckRunOutput,

    /* The name of the check. */
    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "check_suite")
    val checkSuite: CheckRunCheckSuite,

    @SerialName(value = "app")
    val app: IssuePerformedViaGithubApp,

    /* Pull requests that are open with a `head_sha` or `head_branch` that matches the check. The returned pull requests do not necessarily indicate pull requests that triggered the check. */
    @SerialName(value = "pull_requests")
    val pullRequests: kotlin.collections.List<PullRequestMinimal>,

    @SerialName(value = "deployment")
    val deployment: DeploymentSimple? = null

) {

    /**
     * The phase of the lifecycle that the check is currently in. Statuses of waiting, requested, and pending are reserved for GitHub Actions check runs.
     *
     * Values: queued,in_progress,completed,waiting,requested,pending
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "queued") queued("queued"),
        @SerialName(value = "in_progress") in_progress("in_progress"),
        @SerialName(value = "completed") completed("completed"),
        @SerialName(value = "waiting") waiting("waiting"),
        @SerialName(value = "requested") requested("requested"),
        @SerialName(value = "pending") pending("pending");
    }
    /**
     * 
     *
     * Values: success,failure,neutral,cancelled,skipped,timed_out,action_required,`null`
     */
    @Serializable
    enum class Conclusion(val value: kotlin.String) {
        @SerialName(value = "success") success("success"),
        @SerialName(value = "failure") failure("failure"),
        @SerialName(value = "neutral") neutral("neutral"),
        @SerialName(value = "cancelled") cancelled("cancelled"),
        @SerialName(value = "skipped") skipped("skipped"),
        @SerialName(value = "timed_out") timed_out("timed_out"),
        @SerialName(value = "action_required") action_required("action_required"),
        @SerialName(value = "null") `null`("null");
    }
}

