/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status 
 */
@Serializable

data class ChecksCreateRequestOneOf1 (

    @SerialName(value = "status")
    val status: ChecksCreateRequestOneOf1.Status? = null

) {

    /**
     * 
     *
     * Values: queued,in_progress
     */
    @Serializable
    enum class Status(val value: kotlin.Any) {
        @SerialName(value = "queued") queued("queued"),
        @SerialName(value = "in_progress") in_progress("in_progress");
    }
}

