/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param visibility Which users can access codespaces in the organization. `disabled` means that no users can access codespaces in the organization.
 * @param selectedUsernames The usernames of the organization members who should have access to codespaces in the organization. Required when `visibility` is `selected_members`. The provided list of usernames will replace any existing value.
 */
@Serializable

data class CodespacesSetCodespacesAccessRequest (

    /* Which users can access codespaces in the organization. `disabled` means that no users can access codespaces in the organization. */
    @SerialName(value = "visibility")
    val visibility: CodespacesSetCodespacesAccessRequest.Visibility,

    /* The usernames of the organization members who should have access to codespaces in the organization. Required when `visibility` is `selected_members`. The provided list of usernames will replace any existing value. */
    @SerialName(value = "selected_usernames")
    val selectedUsernames: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * Which users can access codespaces in the organization. `disabled` means that no users can access codespaces in the organization.
     *
     * Values: disabled,selected_members,all_members,all_members_and_outside_collaborators
     */
    @Serializable
    enum class Visibility(val value: kotlin.String) {
        @SerialName(value = "disabled") disabled("disabled"),
        @SerialName(value = "selected_members") selected_members("selected_members"),
        @SerialName(value = "all_members") all_members("all_members"),
        @SerialName(value = "all_members_and_outside_collaborators") all_members_and_outside_collaborators("all_members_and_outside_collaborators");
    }
}

