/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The public key used for setting Codespaces secrets.
 *
 * @param keyId The identifier for the key.
 * @param key The Base64 encoded public key.
 * @param id 
 * @param url 
 * @param title 
 * @param createdAt 
 */
@Serializable

data class CodespacesPublicKey (

    /* The identifier for the key. */
    @SerialName(value = "key_id")
    val keyId: kotlin.String,

    /* The Base64 encoded public key. */
    @SerialName(value = "key")
    val key: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null

)

