/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param location 
 * @param devcontainerPath 
 */
@Serializable

data class CodespacesPreFlightWithRepoForAuthenticatedUser200ResponseDefaults (

    @SerialName(value = "location")
    val location: kotlin.String = "push",

    @SerialName(value = "devcontainer_path")
    val devcontainerPath: kotlin.String?

)

