/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id An identifier for the upload.
 * @param url The REST API URL for checking the status of the upload.
 */
@Serializable

data class CodeScanningSarifsReceipt (

    /* An identifier for the upload. */
    @SerialName(value = "id")
    val id: kotlin.String? = null,

    /* The REST API URL for checking the status of the upload. */
    @Contextual @SerialName(value = "url")
    val url: java.net.URI? = null

)

