/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Pull request number for this codespace
 *
 * @param pullRequestNumber Pull request number
 * @param repositoryId Repository id for this codespace
 */
@Serializable

data class CodespacesCreateForAuthenticatedUserRequestOneOf1PullRequest (

    /* Pull request number */
    @SerialName(value = "pull_request_number")
    val pullRequestNumber: kotlin.Int,

    /* Repository id for this codespace */
    @SerialName(value = "repository_id")
    val repositoryId: kotlin.Int

)

