/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Secrets for a GitHub Codespace.
 *
 * @param name The name of the secret
 * @param createdAt The date and time at which the secret was created, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ.
 * @param updatedAt The date and time at which the secret was created, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ.
 * @param visibility The type of repositories in the organization that the secret is visible to
 * @param selectedRepositoriesUrl The API URL at which the list of repositories this secret is visible to can be retrieved
 */
@Serializable

data class CodespacesOrgSecret (

    /* The name of the secret */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The date and time at which the secret was created, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant,

    /* The date and time at which the secret was created, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlinx.datetime.Instant,

    /* The type of repositories in the organization that the secret is visible to */
    @SerialName(value = "visibility")
    val visibility: CodespacesOrgSecret.Visibility,

    /* The API URL at which the list of repositories this secret is visible to can be retrieved */
    @Contextual @SerialName(value = "selected_repositories_url")
    val selectedRepositoriesUrl: java.net.URI? = null

) {

    /**
     * The type of repositories in the organization that the secret is visible to
     *
     * Values: all,`private`,selected
     */
    @Serializable
    enum class Visibility(val value: kotlin.String) {
        @SerialName(value = "all") all("all"),
        @SerialName(value = "private") `private`("private"),
        @SerialName(value = "selected") selected("selected");
    }
}

