/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Committer

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param author 
 * @param committer 
 * @param distinct Whether this commit is distinct from any that have been pushed before.
 * @param id 
 * @param message The commit message.
 * @param timestamp The ISO 8601 timestamp of the commit.
 * @param treeId 
 * @param url URL that points to the commit API resource.
 * @param added An array of files added in the commit. A maximum of 3000 changed files will be reported per commit.
 * @param modified An array of files modified by the commit. A maximum of 3000 changed files will be reported per commit.
 * @param removed An array of files removed in the commit. A maximum of 3000 changed files will be reported per commit.
 */
@Serializable

data class Commit (

    @SerialName(value = "author")
    val author: Committer,

    @SerialName(value = "committer")
    val committer: Committer,

    /* Whether this commit is distinct from any that have been pushed before. */
    @SerialName(value = "distinct")
    val distinct: kotlin.Boolean,

    @SerialName(value = "id")
    val id: kotlin.String,

    /* The commit message. */
    @SerialName(value = "message")
    val message: kotlin.String,

    /* The ISO 8601 timestamp of the commit. */
    @Contextual @SerialName(value = "timestamp")
    val timestamp: kotlinx.datetime.Instant,

    @SerialName(value = "tree_id")
    val treeId: kotlin.String,

    /* URL that points to the commit API resource. */
    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    /* An array of files added in the commit. A maximum of 3000 changed files will be reported per commit. */
    @SerialName(value = "added")
    val added: kotlin.collections.List<kotlin.String>? = null,

    /* An array of files modified by the commit. A maximum of 3000 changed files will be reported per commit. */
    @SerialName(value = "modified")
    val modified: kotlin.collections.List<kotlin.String>? = null,

    /* An array of files removed in the commit. A maximum of 3000 changed files will be reported per commit. */
    @SerialName(value = "removed")
    val removed: kotlin.collections.List<kotlin.String>? = null

)

