/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CommitCommitAuthor
import org.openapitools.client.models.CommitSearchResultItemCommitAuthor
import org.openapitools.client.models.ShortBranchCommit
import org.openapitools.client.models.Verification

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param author 
 * @param committer 
 * @param commentCount 
 * @param message 
 * @param tree 
 * @param url 
 * @param verification 
 */
@Serializable

data class CommitSearchResultItemCommit (

    @SerialName(value = "author")
    val author: CommitSearchResultItemCommitAuthor,

    @SerialName(value = "committer")
    val committer: CommitCommitAuthor,

    @SerialName(value = "comment_count")
    val commentCount: kotlin.Int,

    @SerialName(value = "message")
    val message: kotlin.String,

    @SerialName(value = "tree")
    val tree: ShortBranchCommit,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @SerialName(value = "verification")
    val verification: Verification? = null

)

