/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id ID of the created snapshot.
 * @param createdAt The time at which the snapshot was created.
 * @param result Either \"SUCCESS\", \"ACCEPTED\", or \"INVALID\". \"SUCCESS\" indicates that the snapshot was successfully created and the repository's dependencies were updated. \"ACCEPTED\" indicates that the snapshot was successfully created, but the repository's dependencies were not updated. \"INVALID\" indicates that the snapshot was malformed.
 * @param message A message providing further details about the result, such as why the dependencies were not updated.
 */
@Serializable

data class DependencyGraphCreateRepositorySnapshot201Response (

    /* ID of the created snapshot. */
    @SerialName(value = "id")
    val id: kotlin.Int,

    /* The time at which the snapshot was created. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    /* Either \"SUCCESS\", \"ACCEPTED\", or \"INVALID\". \"SUCCESS\" indicates that the snapshot was successfully created and the repository's dependencies were updated. \"ACCEPTED\" indicates that the snapshot was successfully created, but the repository's dependencies were not updated. \"INVALID\" indicates that the snapshot was malformed. */
    @SerialName(value = "result")
    val result: kotlin.String,

    /* A message providing further details about the result, such as why the dependencies were not updated. */
    @SerialName(value = "message")
    val message: kotlin.String

)

