/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DependabotAlertPackage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Details for the vulnerable dependency.
 *
 * @param `package` 
 * @param manifestPath The full path to the dependency manifest file, relative to the root of the repository.
 * @param scope The execution scope of the vulnerable dependency.
 */
@Serializable

data class DependabotAlertWithRepositoryDependency (

    @SerialName(value = "package")
    val `package`: DependabotAlertPackage? = null,

    /* The full path to the dependency manifest file, relative to the root of the repository. */
    @SerialName(value = "manifest_path")
    val manifestPath: kotlin.String? = null,

    /* The execution scope of the vulnerable dependency. */
    @SerialName(value = "scope")
    val scope: DependabotAlertWithRepositoryDependency.Scope? = null

) {

    /**
     * The execution scope of the vulnerable dependency.
     *
     * Values: development,runtime,`null`
     */
    @Serializable
    enum class Scope(val value: kotlin.String) {
        @SerialName(value = "development") development("development"),
        @SerialName(value = "runtime") runtime("runtime"),
        @SerialName(value = "null") `null`("null");
    }
}

