/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.App3
import org.openapitools.client.models.DeploymentPayload
import org.openapitools.client.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The [deployment](https://docs.github.com/rest/deployments/deployments#list-deployments).
 *
 * @param createdAt 
 * @param creator 
 * @param description 
 * @param environment 
 * @param id 
 * @param nodeId 
 * @param originalEnvironment 
 * @param payload 
 * @param ref 
 * @param repositoryUrl 
 * @param sha 
 * @param statusesUrl 
 * @param task 
 * @param updatedAt 
 * @param url 
 * @param performedViaGithubApp 
 * @param productionEnvironment 
 * @param transientEnvironment 
 */
@Serializable

data class Deployment (

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "creator")
    val creator: User,

    @SerialName(value = "description")
    val description: kotlin.String?,

    @SerialName(value = "environment")
    val environment: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "node_id")
    val nodeId: kotlin.String,

    @SerialName(value = "original_environment")
    val originalEnvironment: kotlin.String,

    @SerialName(value = "payload")
    val payload: DeploymentPayload,

    @SerialName(value = "ref")
    val ref: kotlin.String,

    @Contextual @SerialName(value = "repository_url")
    val repositoryUrl: java.net.URI,

    @SerialName(value = "sha")
    val sha: kotlin.String,

    @Contextual @SerialName(value = "statuses_url")
    val statusesUrl: java.net.URI,

    @SerialName(value = "task")
    val task: kotlin.String,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @SerialName(value = "performed_via_github_app")
    val performedViaGithubApp: App3? = null,

    @SerialName(value = "production_environment")
    val productionEnvironment: kotlin.Boolean? = null,

    @SerialName(value = "transient_environment")
    val transientEnvironment: kotlin.Boolean? = null

)

