/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PendingDeploymentReviewersInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param nodeId 
 * @param type 
 * @param preventSelfReview Whether deployments to this environment can be approved by the user who created the deployment.
 * @param reviewers The people or teams that may approve jobs that reference the environment. You can list up to six users or teams as reviewers. The reviewers must have at least read access to the repository. Only one of the required reviewers needs to approve the job for it to proceed.
 */
@Serializable

data class EnvironmentProtectionRulesInnerAnyOf1 (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "node_id")
    val nodeId: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    /* Whether deployments to this environment can be approved by the user who created the deployment. */
    @SerialName(value = "prevent_self_review")
    val preventSelfReview: kotlin.Boolean? = null,

    /* The people or teams that may approve jobs that reference the environment. You can list up to six users or teams as reviewers. The reviewers must have at least read access to the repository. Only one of the required reviewers needs to approve the job for it to proceed. */
    @SerialName(value = "reviewers")
    val reviewers: kotlin.collections.List<PendingDeploymentReviewersInner>? = null

)

