/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param htmlUrl 
 * @param sha 
 */
@Serializable

data class FileCommitCommitParentsInner (

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String? = null,

    @SerialName(value = "sha")
    val sha: kotlin.String? = null

)

