/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sha 
 * @param type 
 * @param url 
 */
@Serializable

data class GitTagObject (

    @SerialName(value = "sha")
    val sha: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI

)

