/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IssuesAddLabelsRequestOneOf
import org.openapitools.client.models.IssuesSetLabelsRequestOneOf1

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param labels 
 */
@Serializable

data class IssuesAddLabelsRequest (

    @Contextual @SerialName(value = "labels")
    val labels: kotlin.Any? = null

)

