/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuthorAssociation
import org.openapitools.client.models.IntegrationOwner
import org.openapitools.client.models.IssueMilestone
import org.openapitools.client.models.IssuePerformedViaGithubApp
import org.openapitools.client.models.IssuePullRequest
import org.openapitools.client.models.IssueSearchResultItemLabelsInner
import org.openapitools.client.models.ReactionRollup
import org.openapitools.client.models.Repository
import org.openapitools.client.models.SearchResultTextMatchesInner
import org.openapitools.client.models.SimpleUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Issue Search Result Item
 *
 * @param url 
 * @param repositoryUrl 
 * @param labelsUrl 
 * @param commentsUrl 
 * @param eventsUrl 
 * @param htmlUrl 
 * @param id 
 * @param nodeId 
 * @param number 
 * @param title 
 * @param locked 
 * @param user 
 * @param labels 
 * @param state 
 * @param assignee 
 * @param milestone 
 * @param comments 
 * @param createdAt 
 * @param updatedAt 
 * @param closedAt 
 * @param score 
 * @param authorAssociation 
 * @param activeLockReason 
 * @param assignees 
 * @param stateReason 
 * @param textMatches 
 * @param pullRequest 
 * @param body 
 * @param draft 
 * @param repository 
 * @param bodyHtml 
 * @param bodyText 
 * @param timelineUrl 
 * @param performedViaGithubApp 
 * @param reactions 
 */
@Serializable

data class IssueSearchResultItem (

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @Contextual @SerialName(value = "repository_url")
    val repositoryUrl: java.net.URI,

    @SerialName(value = "labels_url")
    val labelsUrl: kotlin.String,

    @Contextual @SerialName(value = "comments_url")
    val commentsUrl: java.net.URI,

    @Contextual @SerialName(value = "events_url")
    val eventsUrl: java.net.URI,

    @Contextual @SerialName(value = "html_url")
    val htmlUrl: java.net.URI,

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "node_id")
    val nodeId: kotlin.String,

    @SerialName(value = "number")
    val number: kotlin.Int,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "locked")
    val locked: kotlin.Boolean,

    @SerialName(value = "user")
    val user: IntegrationOwner,

    @SerialName(value = "labels")
    val labels: kotlin.collections.List<IssueSearchResultItemLabelsInner>,

    @SerialName(value = "state")
    val state: kotlin.String,

    @SerialName(value = "assignee")
    val assignee: IntegrationOwner,

    @SerialName(value = "milestone")
    val milestone: IssueMilestone,

    @SerialName(value = "comments")
    val comments: kotlin.Int,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlinx.datetime.Instant,

    @Contextual @SerialName(value = "closed_at")
    val closedAt: kotlinx.datetime.Instant?,

    @Contextual @SerialName(value = "score")
    val score: java.math.BigDecimal,

    @Contextual @SerialName(value = "author_association")
    val authorAssociation: AuthorAssociation,

    @SerialName(value = "active_lock_reason")
    val activeLockReason: kotlin.String? = null,

    @SerialName(value = "assignees")
    val assignees: kotlin.collections.List<SimpleUser>? = null,

    @SerialName(value = "state_reason")
    val stateReason: kotlin.String? = null,

    @SerialName(value = "text_matches")
    val textMatches: kotlin.collections.List<SearchResultTextMatchesInner>? = null,

    @SerialName(value = "pull_request")
    val pullRequest: IssuePullRequest? = null,

    @SerialName(value = "body")
    val body: kotlin.String? = null,

    @SerialName(value = "draft")
    val draft: kotlin.Boolean? = null,

    @SerialName(value = "repository")
    val repository: Repository? = null,

    @SerialName(value = "body_html")
    val bodyHtml: kotlin.String? = null,

    @SerialName(value = "body_text")
    val bodyText: kotlin.String? = null,

    @Contextual @SerialName(value = "timeline_url")
    val timelineUrl: java.net.URI? = null,

    @SerialName(value = "performed_via_github_app")
    val performedViaGithubApp: IssuePerformedViaGithubApp? = null,

    @SerialName(value = "reactions")
    val reactions: ReactionRollup? = null

)

