/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IssuesCreateRequestLabelsInnerOneOf

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param color 
 */
@Serializable

data class IssuesCreateRequestLabelsInner (

    @Contextual @SerialName(value = "id")
    val id: kotlin.Any? = null,

    @Contextual @SerialName(value = "name")
    val name: kotlin.Any? = null,

    @Contextual @SerialName(value = "description")
    val description: kotlin.Any? = null,

    @Contextual @SerialName(value = "color")
    val color: kotlin.Any? = null

)

