/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param text The Markdown text to render in HTML.
 * @param mode The rendering mode.
 * @param context The repository context to use when creating references in `gfm` mode.  For example, setting `context` to `octo-org/octo-repo` will change the text `#42` into an HTML link to issue 42 in the `octo-org/octo-repo` repository.
 */
@Serializable

data class MarkdownRenderRequest (

    /* The Markdown text to render in HTML. */
    @SerialName(value = "text")
    val text: kotlin.String,

    /* The rendering mode. */
    @SerialName(value = "mode")
    val mode: MarkdownRenderRequest.Mode? = Mode.markdown,

    /* The repository context to use when creating references in `gfm` mode.  For example, setting `context` to `octo-org/octo-repo` will change the text `#42` into an HTML link to issue 42 in the `octo-org/octo-repo` repository. */
    @SerialName(value = "context")
    val context: kotlin.String? = null

) {

    /**
     * The rendering mode.
     *
     * Values: markdown,gfm
     */
    @Serializable
    enum class Mode(val value: kotlin.String) {
        @SerialName(value = "markdown") markdown("markdown"),
        @SerialName(value = "gfm") gfm("gfm");
    }
}

