/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param vcsUrl The URL of the originating repository.
 * @param vcs The originating VCS type. Without this parameter, the import job will take additional time to detect the VCS type before beginning the import. This detection step will be reflected in the response.
 * @param vcsUsername If authentication is required, the username to provide to `vcs_url`.
 * @param vcsPassword If authentication is required, the password to provide to `vcs_url`.
 * @param tfvcProject For a tfvc import, the name of the project that is being imported.
 */
@Serializable

data class MigrationsStartImportRequest (

    /* The URL of the originating repository. */
    @SerialName(value = "vcs_url")
    val vcsUrl: kotlin.String,

    /* The originating VCS type. Without this parameter, the import job will take additional time to detect the VCS type before beginning the import. This detection step will be reflected in the response. */
    @SerialName(value = "vcs")
    val vcs: MigrationsStartImportRequest.Vcs? = null,

    /* If authentication is required, the username to provide to `vcs_url`. */
    @SerialName(value = "vcs_username")
    val vcsUsername: kotlin.String? = null,

    /* If authentication is required, the password to provide to `vcs_url`. */
    @SerialName(value = "vcs_password")
    val vcsPassword: kotlin.String? = null,

    /* For a tfvc import, the name of the project that is being imported. */
    @SerialName(value = "tfvc_project")
    val tfvcProject: kotlin.String? = null

) {

    /**
     * The originating VCS type. Without this parameter, the import job will take additional time to detect the VCS type before beginning the import. This detection step will be reflected in the response.
     *
     * Values: subversion,git,mercurial,tfvc
     */
    @Serializable
    enum class Vcs(val value: kotlin.String) {
        @SerialName(value = "subversion") subversion("subversion"),
        @SerialName(value = "git") git("git"),
        @SerialName(value = "mercurial") mercurial("mercurial"),
        @SerialName(value = "tfvc") tfvc("tfvc");
    }
}

