/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param insecureSsl 
 * @param contentType 
 * @param secret 
 */
@Serializable

data class OrgHookConfig (

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "insecure_ssl")
    val insecureSsl: kotlin.String? = null,

    @SerialName(value = "content_type")
    val contentType: kotlin.String? = null,

    @SerialName(value = "secret")
    val secret: kotlin.String? = null

)

