/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param state The state that the membership should be in. Only `\"active\"` will be accepted.
 */
@Serializable

data class OrgsUpdateMembershipForAuthenticatedUserRequest (

    /* The state that the membership should be in. Only `\"active\"` will be accepted. */
    @SerialName(value = "state")
    val state: OrgsUpdateMembershipForAuthenticatedUserRequest.State

) {

    /**
     * The state that the membership should be in. Only `\"active\"` will be accepted.
     *
     * Values: active
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active") active("active");
    }
}

