/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CodeOfConduct
import org.openapitools.client.models.MinimalRepository
import org.openapitools.client.models.MinimalRepositoryLicense
import org.openapitools.client.models.MinimalRepositoryPermissions
import org.openapitools.client.models.SecurityAndAnalysis
import org.openapitools.client.models.SimpleUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param nodeId 
 * @param name 
 * @param fullName 
 * @param owner 
 * @param `private` 
 * @param htmlUrl 
 * @param description 
 * @param fork 
 * @param url 
 * @param archiveUrl 
 * @param assigneesUrl 
 * @param blobsUrl 
 * @param branchesUrl 
 * @param collaboratorsUrl 
 * @param commentsUrl 
 * @param commitsUrl 
 * @param compareUrl 
 * @param contentsUrl 
 * @param contributorsUrl 
 * @param deploymentsUrl 
 * @param downloadsUrl 
 * @param eventsUrl 
 * @param forksUrl 
 * @param gitCommitsUrl 
 * @param gitRefsUrl 
 * @param gitTagsUrl 
 * @param issueCommentUrl 
 * @param issueEventsUrl 
 * @param issuesUrl 
 * @param keysUrl 
 * @param labelsUrl 
 * @param languagesUrl 
 * @param mergesUrl 
 * @param milestonesUrl 
 * @param notificationsUrl 
 * @param pullsUrl 
 * @param releasesUrl 
 * @param stargazersUrl 
 * @param statusesUrl 
 * @param subscribersUrl 
 * @param subscriptionUrl 
 * @param tagsUrl 
 * @param teamsUrl 
 * @param treesUrl 
 * @param hooksUrl 
 * @param gitUrl 
 * @param sshUrl 
 * @param cloneUrl 
 * @param mirrorUrl 
 * @param svnUrl 
 * @param homepage 
 * @param language 
 * @param forksCount 
 * @param stargazersCount 
 * @param watchersCount 
 * @param propertySize The size of the repository, in kilobytes. Size is calculated hourly. When a repository is initially created, the size is 0.
 * @param defaultBranch 
 * @param openIssuesCount 
 * @param isTemplate 
 * @param topics 
 * @param hasIssues 
 * @param hasProjects 
 * @param hasWiki 
 * @param hasPages 
 * @param hasDownloads 
 * @param hasDiscussions 
 * @param archived 
 * @param disabled 
 * @param visibility 
 * @param pushedAt 
 * @param createdAt 
 * @param updatedAt 
 * @param permissions 
 * @param roleName 
 * @param tempCloneToken 
 * @param deleteBranchOnMerge 
 * @param subscribersCount 
 * @param networkCount 
 * @param codeOfConduct 
 * @param license 
 * @param forks 
 * @param openIssues 
 * @param watchers 
 * @param allowForking 
 * @param webCommitSignoffRequired 
 * @param securityAndAnalysis 
 */
@Serializable

data class PackageRepository (

    @Contextual @SerialName(value = "id")
    val id: kotlin.Any?,

    @Contextual @SerialName(value = "node_id")
    val nodeId: kotlin.Any?,

    @Contextual @SerialName(value = "name")
    val name: kotlin.Any?,

    @Contextual @SerialName(value = "full_name")
    val fullName: kotlin.Any?,

    @SerialName(value = "owner")
    val owner: SimpleUser,

    @Contextual @SerialName(value = "private")
    val `private`: kotlin.Any?,

    @Contextual @SerialName(value = "html_url")
    val htmlUrl: kotlin.Any?,

    @Contextual @SerialName(value = "description")
    val description: kotlin.Any?,

    @Contextual @SerialName(value = "fork")
    val fork: kotlin.Any?,

    @Contextual @SerialName(value = "url")
    val url: kotlin.Any?,

    @Contextual @SerialName(value = "archive_url")
    val archiveUrl: kotlin.Any?,

    @Contextual @SerialName(value = "assignees_url")
    val assigneesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "blobs_url")
    val blobsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "branches_url")
    val branchesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "collaborators_url")
    val collaboratorsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "comments_url")
    val commentsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "commits_url")
    val commitsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "compare_url")
    val compareUrl: kotlin.Any?,

    @Contextual @SerialName(value = "contents_url")
    val contentsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "contributors_url")
    val contributorsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "deployments_url")
    val deploymentsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "downloads_url")
    val downloadsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "events_url")
    val eventsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "forks_url")
    val forksUrl: kotlin.Any?,

    @Contextual @SerialName(value = "git_commits_url")
    val gitCommitsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "git_refs_url")
    val gitRefsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "git_tags_url")
    val gitTagsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "issue_comment_url")
    val issueCommentUrl: kotlin.Any?,

    @Contextual @SerialName(value = "issue_events_url")
    val issueEventsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "issues_url")
    val issuesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "keys_url")
    val keysUrl: kotlin.Any?,

    @Contextual @SerialName(value = "labels_url")
    val labelsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "languages_url")
    val languagesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "merges_url")
    val mergesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "milestones_url")
    val milestonesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "notifications_url")
    val notificationsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "pulls_url")
    val pullsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "releases_url")
    val releasesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "stargazers_url")
    val stargazersUrl: kotlin.Any?,

    @Contextual @SerialName(value = "statuses_url")
    val statusesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "subscribers_url")
    val subscribersUrl: kotlin.Any?,

    @Contextual @SerialName(value = "subscription_url")
    val subscriptionUrl: kotlin.Any?,

    @Contextual @SerialName(value = "tags_url")
    val tagsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "teams_url")
    val teamsUrl: kotlin.Any?,

    @Contextual @SerialName(value = "trees_url")
    val treesUrl: kotlin.Any?,

    @Contextual @SerialName(value = "hooks_url")
    val hooksUrl: kotlin.Any?,

    @Contextual @SerialName(value = "git_url")
    val gitUrl: kotlin.Any? = null,

    @Contextual @SerialName(value = "ssh_url")
    val sshUrl: kotlin.Any? = null,

    @Contextual @SerialName(value = "clone_url")
    val cloneUrl: kotlin.Any? = null,

    @Contextual @SerialName(value = "mirror_url")
    val mirrorUrl: kotlin.Any? = null,

    @Contextual @SerialName(value = "svn_url")
    val svnUrl: kotlin.Any? = null,

    @Contextual @SerialName(value = "homepage")
    val homepage: kotlin.Any? = null,

    @Contextual @SerialName(value = "language")
    val language: kotlin.Any? = null,

    @Contextual @SerialName(value = "forks_count")
    val forksCount: kotlin.Any? = null,

    @Contextual @SerialName(value = "stargazers_count")
    val stargazersCount: kotlin.Any? = null,

    @Contextual @SerialName(value = "watchers_count")
    val watchersCount: kotlin.Any? = null,

    /* The size of the repository, in kilobytes. Size is calculated hourly. When a repository is initially created, the size is 0. */
    @Contextual @SerialName(value = "size")
    val propertySize: kotlin.Any? = null,

    @Contextual @SerialName(value = "default_branch")
    val defaultBranch: kotlin.Any? = null,

    @Contextual @SerialName(value = "open_issues_count")
    val openIssuesCount: kotlin.Any? = null,

    @Contextual @SerialName(value = "is_template")
    val isTemplate: kotlin.Any? = null,

    @Contextual @SerialName(value = "topics")
    val topics: kotlin.Any? = null,

    @Contextual @SerialName(value = "has_issues")
    val hasIssues: kotlin.Any? = null,

    @Contextual @SerialName(value = "has_projects")
    val hasProjects: kotlin.Any? = null,

    @Contextual @SerialName(value = "has_wiki")
    val hasWiki: kotlin.Any? = null,

    @Contextual @SerialName(value = "has_pages")
    val hasPages: kotlin.Any? = null,

    @Contextual @SerialName(value = "has_downloads")
    val hasDownloads: kotlin.Any? = null,

    @Contextual @SerialName(value = "has_discussions")
    val hasDiscussions: kotlin.Any? = null,

    @Contextual @SerialName(value = "archived")
    val archived: kotlin.Any? = null,

    @Contextual @SerialName(value = "disabled")
    val disabled: kotlin.Any? = null,

    @Contextual @SerialName(value = "visibility")
    val visibility: kotlin.Any? = null,

    @Contextual @SerialName(value = "pushed_at")
    val pushedAt: kotlin.Any? = null,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.Any? = null,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.Any? = null,

    @SerialName(value = "permissions")
    val permissions: MinimalRepositoryPermissions? = null,

    @Contextual @SerialName(value = "role_name")
    val roleName: kotlin.Any? = null,

    @Contextual @SerialName(value = "temp_clone_token")
    val tempCloneToken: kotlin.Any? = null,

    @Contextual @SerialName(value = "delete_branch_on_merge")
    val deleteBranchOnMerge: kotlin.Any? = null,

    @Contextual @SerialName(value = "subscribers_count")
    val subscribersCount: kotlin.Any? = null,

    @Contextual @SerialName(value = "network_count")
    val networkCount: kotlin.Any? = null,

    @SerialName(value = "code_of_conduct")
    val codeOfConduct: CodeOfConduct? = null,

    @SerialName(value = "license")
    val license: MinimalRepositoryLicense? = null,

    @Contextual @SerialName(value = "forks")
    val forks: kotlin.Any? = null,

    @Contextual @SerialName(value = "open_issues")
    val openIssues: kotlin.Any? = null,

    @Contextual @SerialName(value = "watchers")
    val watchers: kotlin.Any? = null,

    @Contextual @SerialName(value = "allow_forking")
    val allowForking: kotlin.Any? = null,

    @Contextual @SerialName(value = "web_commit_signoff_required")
    val webCommitSignoffRequired: kotlin.Any? = null,

    @SerialName(value = "security_and_analysis")
    val securityAndAnalysis: SecurityAndAnalysis? = null

)

