/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status The current status of the deployment.
 */
@Serializable

data class PagesDeploymentStatus (

    /* The current status of the deployment. */
    @SerialName(value = "status")
    val status: PagesDeploymentStatus.Status? = null

) {

    /**
     * The current status of the deployment.
     *
     * Values: deployment_in_progress,syncing_files,finished_file_sync,updating_pages,purging_cdn,deployment_cancelled,deployment_failed,deployment_content_failed,deployment_attempt_error,deployment_lost,succeed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "deployment_in_progress") deployment_in_progress("deployment_in_progress"),
        @SerialName(value = "syncing_files") syncing_files("syncing_files"),
        @SerialName(value = "finished_file_sync") finished_file_sync("finished_file_sync"),
        @SerialName(value = "updating_pages") updating_pages("updating_pages"),
        @SerialName(value = "purging_cdn") purging_cdn("purging_cdn"),
        @SerialName(value = "deployment_cancelled") deployment_cancelled("deployment_cancelled"),
        @SerialName(value = "deployment_failed") deployment_failed("deployment_failed"),
        @SerialName(value = "deployment_content_failed") deployment_content_failed("deployment_content_failed"),
        @SerialName(value = "deployment_attempt_error") deployment_attempt_error("deployment_attempt_error"),
        @SerialName(value = "deployment_lost") deployment_lost("deployment_lost"),
        @SerialName(value = "succeed") succeed("succeed");
    }
}

