/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Porter Large File
 *
 * @param refName 
 * @param path 
 * @param oid 
 * @param propertySize 
 */
@Serializable

data class PorterLargeFile (

    @SerialName(value = "ref_name")
    val refName: kotlin.String,

    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "oid")
    val oid: kotlin.String,

    @SerialName(value = "size")
    val propertySize: kotlin.Int

)

