/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cardsUrl 
 * @param createdAt 
 * @param id The unique identifier of the project column
 * @param name Name of the project column
 * @param nodeId 
 * @param projectUrl 
 * @param updatedAt 
 * @param url 
 * @param afterId 
 */
@Serializable

data class ProjectColumn (

    @Contextual @SerialName(value = "cards_url")
    val cardsUrl: java.net.URI,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant,

    /* The unique identifier of the project column */
    @SerialName(value = "id")
    val id: kotlin.Int,

    /* Name of the project column */
    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "node_id")
    val nodeId: kotlin.String,

    @Contextual @SerialName(value = "project_url")
    val projectUrl: java.net.URI,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlinx.datetime.Instant,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @SerialName(value = "after_id")
    val afterId: kotlin.Int? = null

)

