/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Link

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param comments 
 * @param commits 
 * @param statuses 
 * @param html 
 * @param issue 
 * @param reviewComments 
 * @param reviewComment 
 * @param self 
 */
@Serializable

data class PullRequestSimpleLinks (

    @SerialName(value = "comments")
    val comments: Link,

    @SerialName(value = "commits")
    val commits: Link,

    @SerialName(value = "statuses")
    val statuses: Link,

    @SerialName(value = "html")
    val html: Link,

    @SerialName(value = "issue")
    val issue: Link,

    @SerialName(value = "review_comments")
    val reviewComments: Link,

    @SerialName(value = "review_comment")
    val reviewComment: Link,

    @SerialName(value = "self")
    val self: Link

)

