/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param nodeId 
 * @param url 
 * @param name 
 * @param description 
 * @param color 
 * @param default 
 */
@Serializable

data class PullRequestLabelsInner (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "node_id")
    val nodeId: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String?,

    @SerialName(value = "color")
    val color: kotlin.String,

    @SerialName(value = "default")
    val default: kotlin.Boolean

)

