/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param include Array of repository names or patterns to include. One of these patterns must match for the condition to pass. Also accepts `~ALL` to include all repositories.
 * @param exclude Array of repository names or patterns to exclude. The condition will not pass if any of these patterns match.
 * @param `protected` Whether renaming of target repositories is prevented.
 */
@Serializable

data class RepositoryRulesetConditionsRepositoryNameTargetRepositoryName (

    /* Array of repository names or patterns to include. One of these patterns must match for the condition to pass. Also accepts `~ALL` to include all repositories. */
    @SerialName(value = "include")
    val include: kotlin.collections.List<kotlin.String>? = null,

    /* Array of repository names or patterns to exclude. The condition will not pass if any of these patterns match. */
    @SerialName(value = "exclude")
    val exclude: kotlin.collections.List<kotlin.String>? = null,

    /* Whether renaming of target repositories is prevented. */
    @SerialName(value = "protected")
    val `protected`: kotlin.Boolean? = null

)

