/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param integrationId The ID of the custom app that will be enabled on the environment.
 */
@Serializable

data class ReposCreateDeploymentProtectionRuleRequest (

    /* The ID of the custom app that will be enabled on the environment. */
    @SerialName(value = "integration_id")
    val integrationId: kotlin.Int? = null

)

