/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Repository invitations let you manage who you collaborate with.
 *
 * @param subscribed Determines if notifications should be received from this repository.
 * @param ignored Determines if all notifications should be blocked from this repository.
 * @param reason 
 * @param createdAt 
 * @param url 
 * @param repositoryUrl 
 */
@Serializable

data class RepositorySubscription (

    /* Determines if notifications should be received from this repository. */
    @SerialName(value = "subscribed")
    val subscribed: kotlin.Boolean,

    /* Determines if all notifications should be blocked from this repository. */
    @SerialName(value = "ignored")
    val ignored: kotlin.Boolean,

    @SerialName(value = "reason")
    val reason: kotlin.String?,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @Contextual @SerialName(value = "repository_url")
    val repositoryUrl: java.net.URI

)

