/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param newOwner The username or organization name the repository will be transferred to.
 * @param newName The new name to be given to the repository.
 * @param teamIds ID of the team or teams to add to the repository. Teams can only be added to organization-owned repositories.
 */
@Serializable

data class ReposTransferRequest (

    /* The username or organization name the repository will be transferred to. */
    @SerialName(value = "new_owner")
    val newOwner: kotlin.String,

    /* The new name to be given to the repository. */
    @SerialName(value = "new_name")
    val newName: kotlin.String? = null,

    /* ID of the team or teams to add to the repository. Teams can only be added to organization-owned repositories. */
    @SerialName(value = "team_ids")
    val teamIds: kotlin.collections.List<kotlin.Int>? = null

)

