/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param users The username for users
 */
@Serializable

data class ReposSetUserAccessRestrictionsRequestOneOf (

    /* The username for users */
    @SerialName(value = "users")
    val users: kotlin.collections.List<kotlin.String>

)

