/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Required status check
 *
 * @param context The status check context name that must be present on the commit.
 * @param integrationId The optional integration ID that this status check must originate from.
 */
@Serializable

data class RepositoryRuleParamsStatusCheckConfiguration (

    /* The status check context name that must be present on the commit. */
    @SerialName(value = "context")
    val context: kotlin.String,

    /* The optional integration ID that this status check must originate from. */
    @SerialName(value = "integration_id")
    val integrationId: kotlin.Int? = null

)

