/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Parameters for a targeting a repository property
 *
 * @param name The name of the repository property to target
 * @param propertyValues The values to match for the repository property
 */
@Serializable

data class RepositoryRulesetConditionsRepositoryPropertySpec (

    /* The name of the repository property to target */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The values to match for the repository property */
    @SerialName(value = "property_values")
    val propertyValues: kotlin.collections.List<kotlin.String>

)

