/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A label for a self hosted runner
 *
 * @param name Name of the label.
 * @param id Unique identifier of the label.
 * @param type The type of label. Read-only labels are applied automatically when the runner is configured.
 */
@Serializable

data class RunnerLabel (

    /* Name of the label. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* Unique identifier of the label. */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* The type of label. Read-only labels are applied automatically when the runner is configured. */
    @SerialName(value = "type")
    val type: RunnerLabel.Type? = null

) {

    /**
     * The type of label. Read-only labels are applied automatically when the runner is configured.
     *
     * Values: readMinusOnly,custom
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "read-only") readMinusOnly("read-only"),
        @SerialName(value = "custom") custom("custom");
    }
}

