/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents a 'discussion_body' secret scanning location type. This location type shows that a secret was detected in the body of a discussion.
 *
 * @param discussionBodyUrl The URL to the discussion where the secret was detected.
 */
@Serializable

data class SecretScanningLocationDiscussionBody (

    /* The URL to the discussion where the secret was detected. */
    @Contextual @SerialName(value = "discussion_body_url")
    val discussionBodyUrl: java.net.URI

)

