/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Enable or disable Dependabot security updates for the repository.
 *
 * @param status The enablement status of Dependabot security updates for the repository.
 */
@Serializable

data class SecurityAndAnalysisDependabotSecurityUpdates (

    /* The enablement status of Dependabot security updates for the repository. */
    @SerialName(value = "status")
    val status: SecurityAndAnalysisDependabotSecurityUpdates.Status? = null

) {

    /**
     * The enablement status of Dependabot security updates for the repository.
     *
     * Values: enabled,disabled
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "enabled") enabled("enabled"),
        @SerialName(value = "disabled") disabled("disabled");
    }
}

