/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Repository

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Starred Repository
 *
 * @param starredAt 
 * @param repo 
 */
@Serializable

data class StarredRepository (

    @Contextual @SerialName(value = "starred_at")
    val starredAt: kotlinx.datetime.Instant,

    @SerialName(value = "repo")
    val repo: Repository

)

