/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param read 
 * @param write 
 * @param admin 
 */
@Serializable

data class TeamProjectPermissions (

    @SerialName(value = "read")
    val read: kotlin.Boolean,

    @SerialName(value = "write")
    val write: kotlin.Boolean,

    @SerialName(value = "admin")
    val admin: kotlin.Boolean

)

