/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param timestamp 
 * @param uniques 
 * @param count 
 */
@Serializable

data class Traffic (

    @Contextual @SerialName(value = "timestamp")
    val timestamp: kotlinx.datetime.Instant,

    @SerialName(value = "uniques")
    val uniques: kotlin.Int,

    @SerialName(value = "count")
    val count: kotlin.Int

)

