/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The action requested by the user.
 *
 * @param identifier The integrator reference of the action requested by the user.
 */
@Serializable

data class WebhookCheckRunRequestedActionRequestedAction (

    /* The integrator reference of the action requested by the user. */
    @SerialName(value = "identifier")
    val identifier: kotlin.String? = null

)

