/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WebhookLabelEditedChangesColor
import org.openapitools.client.models.WebhookLabelEditedChangesDescription
import org.openapitools.client.models.WebhookLabelEditedChangesName

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The changes to the label if the action was `edited`.
 *
 * @param color 
 * @param description 
 * @param name 
 */
@Serializable

data class WebhookLabelEditedChanges (

    @SerialName(value = "color")
    val color: WebhookLabelEditedChangesColor? = null,

    @SerialName(value = "description")
    val description: WebhookLabelEditedChangesDescription? = null,

    @SerialName(value = "name")
    val name: WebhookLabelEditedChangesName? = null

)

