/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BranchRestrictionPolicyUsersInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param author 
 * @param createdAt 
 * @param draft 
 * @param htmlUrl 
 * @param id 
 * @param name 
 * @param prerelease 
 * @param publishedAt 
 * @param tagName 
 * @param targetCommitish 
 * @param url 
 */
@Serializable

data class WebhookRegistryPackagePublishedRegistryPackagePackageVersionRelease (

    @SerialName(value = "author")
    val author: BranchRestrictionPolicyUsersInner? = null,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "draft")
    val draft: kotlin.Boolean? = null,

    @SerialName(value = "html_url")
    val htmlUrl: kotlin.String? = null,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "prerelease")
    val prerelease: kotlin.Boolean? = null,

    @SerialName(value = "published_at")
    val publishedAt: kotlin.String? = null,

    @SerialName(value = "tag_name")
    val tagName: kotlin.String? = null,

    @SerialName(value = "target_commitish")
    val targetCommitish: kotlin.String? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null

)

