/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WebhookDiscussionCommentEditedChangesBody
import org.openapitools.client.models.WebhookProjectCardEditedChangesNote
import org.openapitools.client.models.WebhookRepositoryEditedChangesTopics

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param defaultBranch 
 * @param description 
 * @param homepage 
 * @param topics 
 */
@Serializable

data class WebhookRepositoryEditedChanges (

    @SerialName(value = "default_branch")
    val defaultBranch: WebhookDiscussionCommentEditedChangesBody? = null,

    @SerialName(value = "description")
    val description: WebhookProjectCardEditedChangesNote? = null,

    @SerialName(value = "homepage")
    val homepage: WebhookProjectCardEditedChangesNote? = null,

    @SerialName(value = "topics")
    val topics: WebhookRepositoryEditedChangesTopics? = null

)

