/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param to Whether this release was explicitly `edited` to be the latest.
 */
@Serializable

data class WebhookReleaseEditedChangesMakeLatest (

    /* Whether this release was explicitly `edited` to be the latest. */
    @SerialName(value = "to")
    val to: kotlin.Boolean

)

