/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WebhookDiscussionCommentEditedChangesBody

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param login 
 * @param slug 
 */
@Serializable

data class WebhookInstallationTargetRenamedChanges (

    @SerialName(value = "login")
    val login: WebhookDiscussionCommentEditedChangesBody? = null,

    @SerialName(value = "slug")
    val slug: WebhookDiscussionCommentEditedChangesBody? = null

)

