/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param from The previous version of the due date if the action was `edited`.
 */
@Serializable

data class WebhookMilestoneEditedChangesDueOn (

    /* The previous version of the due date if the action was `edited`. */
    @SerialName(value = "from")
    val from: kotlin.String

)

