/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CheckRunWithSimpleCheckSuite
import org.openapitools.client.models.OrganizationSimpleWebhooks
import org.openapitools.client.models.RepositoryWebhooks
import org.openapitools.client.models.SimpleInstallation
import org.openapitools.client.models.SimpleUserWebhooks
import org.openapitools.client.models.WebhookCheckRunRequestedActionRequestedAction

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param action 
 * @param checkRun 
 * @param repository 
 * @param sender 
 * @param installation 
 * @param organization 
 * @param requestedAction 
 */
@Serializable

data class WebhookCheckRunRequestedAction (

    @SerialName(value = "action")
    val action: WebhookCheckRunRequestedAction.Action,

    @SerialName(value = "check_run")
    val checkRun: CheckRunWithSimpleCheckSuite,

    @SerialName(value = "repository")
    val repository: RepositoryWebhooks,

    @SerialName(value = "sender")
    val sender: SimpleUserWebhooks,

    @SerialName(value = "installation")
    val installation: SimpleInstallation? = null,

    @SerialName(value = "organization")
    val organization: OrganizationSimpleWebhooks? = null,

    @SerialName(value = "requested_action")
    val requestedAction: WebhookCheckRunRequestedActionRequestedAction? = null

) {

    /**
     * 
     *
     * Values: requested_action
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "requested_action") requested_action("requested_action");
    }
}

