/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WebhookOrganizationRenamedChangesLogin

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param configuration 
 * @param ruleType 
 * @param pattern 
 */
@Serializable

data class WebhookRepositoryRulesetEditedChangesRulesUpdatedInnerChanges (

    @SerialName(value = "configuration")
    val configuration: WebhookOrganizationRenamedChangesLogin? = null,

    @SerialName(value = "rule_type")
    val ruleType: WebhookOrganizationRenamedChangesLogin? = null,

    @SerialName(value = "pattern")
    val pattern: WebhookOrganizationRenamedChangesLogin? = null

)

