/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WebhookDiscussionCategoryChangedChangesCategory

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param category 
 */
@Serializable

data class WebhookDiscussionCategoryChangedChanges (

    @SerialName(value = "category")
    val category: WebhookDiscussionCategoryChangedChangesCategory

)

