/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WebhookProjectsV2ItemEditedChangesOneOfFieldValue

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fieldValue 
 */
@Serializable

data class WebhookProjectsV2ItemEditedChangesOneOf (

    @SerialName(value = "field_value")
    val fieldValue: WebhookProjectsV2ItemEditedChangesOneOfFieldValue

)

