/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MergeGroup
import org.openapitools.client.models.OrganizationSimpleWebhooks
import org.openapitools.client.models.RepositoryWebhooks
import org.openapitools.client.models.SimpleInstallation
import org.openapitools.client.models.SimpleUserWebhooks

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param action 
 * @param mergeGroup 
 * @param reason Explains why the merge group is being destroyed. The group could have been merged, removed from the queue (dequeued), or invalidated by an earlier queue entry being dequeued (invalidated).
 * @param installation 
 * @param organization 
 * @param repository 
 * @param sender 
 */
@Serializable

data class WebhookMergeGroupDestroyed (

    @SerialName(value = "action")
    val action: WebhookMergeGroupDestroyed.Action,

    @SerialName(value = "merge_group")
    val mergeGroup: MergeGroup,

    /* Explains why the merge group is being destroyed. The group could have been merged, removed from the queue (dequeued), or invalidated by an earlier queue entry being dequeued (invalidated). */
    @SerialName(value = "reason")
    val reason: WebhookMergeGroupDestroyed.Reason? = null,

    @SerialName(value = "installation")
    val installation: SimpleInstallation? = null,

    @SerialName(value = "organization")
    val organization: OrganizationSimpleWebhooks? = null,

    @SerialName(value = "repository")
    val repository: RepositoryWebhooks? = null,

    @SerialName(value = "sender")
    val sender: SimpleUserWebhooks? = null

) {

    /**
     * 
     *
     * Values: destroyed
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "destroyed") destroyed("destroyed");
    }
    /**
     * Explains why the merge group is being destroyed. The group could have been merged, removed from the queue (dequeued), or invalidated by an earlier queue entry being dequeued (invalidated).
     *
     * Values: merged,invalidated,dequeued
     */
    @Serializable
    enum class Reason(val value: kotlin.String) {
        @SerialName(value = "merged") merged("merged"),
        @SerialName(value = "invalidated") invalidated("invalidated"),
        @SerialName(value = "dequeued") dequeued("dequeued");
    }
}

