/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrganizationSimpleWebhooks
import org.openapitools.client.models.ProjectsV2Item
import org.openapitools.client.models.SimpleInstallation
import org.openapitools.client.models.SimpleUserWebhooks
import org.openapitools.client.models.WebhookProjectsV2ItemConvertedChanges

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param action 
 * @param changes 
 * @param organization 
 * @param projectsV2Item 
 * @param sender 
 * @param installation 
 */
@Serializable

data class WebhookProjectsV2ItemConverted (

    @SerialName(value = "action")
    val action: WebhookProjectsV2ItemConverted.Action,

    @SerialName(value = "changes")
    val changes: WebhookProjectsV2ItemConvertedChanges,

    @SerialName(value = "organization")
    val organization: OrganizationSimpleWebhooks,

    @SerialName(value = "projects_v2_item")
    val projectsV2Item: ProjectsV2Item,

    @SerialName(value = "sender")
    val sender: SimpleUserWebhooks,

    @SerialName(value = "installation")
    val installation: SimpleInstallation? = null

) {

    /**
     * 
     *
     * Values: converted
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "converted") converted("converted");
    }
}

