/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AlertInstance
import org.openapitools.client.models.WebhookCodeScanningAlertClosedByUserAlertRule
import org.openapitools.client.models.WebhookCodeScanningAlertClosedByUserAlertTool

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The code scanning alert involved in the event.
 *
 * @param createdAt The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ.`
 * @param dismissedAt The time that the alert was dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`.
 * @param dismissedBy 
 * @param dismissedReason The reason for dismissing or closing the alert. Can be one of: `false positive`, `won't fix`, and `used in tests`.
 * @param htmlUrl The GitHub URL of the alert resource.
 * @param number The code scanning alert number.
 * @param rule 
 * @param state State of a code scanning alert.
 * @param tool 
 * @param url 
 * @param mostRecentInstance 
 */
@Serializable

data class WebhookCodeScanningAlertReopenedAlert (

    /* The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ.` */
    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlinx.datetime.Instant,

    /* The time that the alert was dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`. */
    @SerialName(value = "dismissed_at")
    val dismissedAt: kotlin.String?,

    @Contextual @SerialName(value = "dismissed_by")
    val dismissedBy: kotlin.Any?,

    /* The reason for dismissing or closing the alert. Can be one of: `false positive`, `won't fix`, and `used in tests`. */
    @SerialName(value = "dismissed_reason")
    val dismissedReason: kotlin.String?,

    /* The GitHub URL of the alert resource. */
    @Contextual @SerialName(value = "html_url")
    val htmlUrl: java.net.URI,

    /* The code scanning alert number. */
    @SerialName(value = "number")
    val number: kotlin.Int,

    @SerialName(value = "rule")
    val rule: WebhookCodeScanningAlertClosedByUserAlertRule,

    /* State of a code scanning alert. */
    @SerialName(value = "state")
    val state: WebhookCodeScanningAlertReopenedAlert.State,

    @SerialName(value = "tool")
    val tool: WebhookCodeScanningAlertClosedByUserAlertTool,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @SerialName(value = "most_recent_instance")
    val mostRecentInstance: AlertInstance? = null

) {

    /**
     * State of a code scanning alert.
     *
     * Values: `open`,dismissed,fixed
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "open") `open`("open"),
        @SerialName(value = "dismissed") dismissed("dismissed"),
        @SerialName(value = "fixed") fixed("fixed");
    }
}

