/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EnterpriseWebhooks
import org.openapitools.client.models.OrgCustomProperty
import org.openapitools.client.models.OrganizationSimpleWebhooks
import org.openapitools.client.models.SimpleInstallation
import org.openapitools.client.models.SimpleUserWebhooks

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param action 
 * @param definition 
 * @param organization 
 * @param enterprise 
 * @param installation 
 * @param sender 
 */
@Serializable

data class WebhookCustomPropertyCreated (

    @SerialName(value = "action")
    val action: WebhookCustomPropertyCreated.Action,

    @SerialName(value = "definition")
    val definition: OrgCustomProperty,

    @SerialName(value = "organization")
    val organization: OrganizationSimpleWebhooks,

    @SerialName(value = "enterprise")
    val enterprise: EnterpriseWebhooks? = null,

    @SerialName(value = "installation")
    val installation: SimpleInstallation? = null,

    @SerialName(value = "sender")
    val sender: SimpleUserWebhooks? = null

) {

    /**
     * 
     *
     * Values: created
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "created") created("created");
    }
}

