/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param aboutUrl 
 * @param name 
 * @param type 
 * @param url 
 * @param vendor 
 */
@Serializable

data class WebhookPackagePublishedPackageRegistry (

    @Contextual @SerialName(value = "about_url")
    val aboutUrl: java.net.URI,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @SerialName(value = "vendor")
    val vendor: kotlin.String

)

