/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.User
import org.openapitools.client.models.WebhookPullRequestReviewDismissedReviewLinks

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The review that was affected.
 *
 * @param links 
 * @param authorAssociation How the author is associated with the repository.
 * @param body The text of the review.
 * @param commitId A commit SHA for the review.
 * @param htmlUrl 
 * @param id Unique identifier of the review
 * @param nodeId 
 * @param pullRequestUrl 
 * @param state 
 * @param submittedAt 
 * @param user 
 */
@Serializable

data class WebhookPullRequestReviewEditedReview (

    @SerialName(value = "_links")
    val links: WebhookPullRequestReviewDismissedReviewLinks,

    /* How the author is associated with the repository. */
    @SerialName(value = "author_association")
    val authorAssociation: WebhookPullRequestReviewEditedReview.AuthorAssociation,

    /* The text of the review. */
    @SerialName(value = "body")
    val body: kotlin.String?,

    /* A commit SHA for the review. */
    @SerialName(value = "commit_id")
    val commitId: kotlin.String,

    @Contextual @SerialName(value = "html_url")
    val htmlUrl: java.net.URI,

    /* Unique identifier of the review */
    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "node_id")
    val nodeId: kotlin.String,

    @Contextual @SerialName(value = "pull_request_url")
    val pullRequestUrl: java.net.URI,

    @SerialName(value = "state")
    val state: kotlin.String,

    @Contextual @SerialName(value = "submitted_at")
    val submittedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "user")
    val user: User

) {

    /**
     * How the author is associated with the repository.
     *
     * Values: COLLABORATOR,CONTRIBUTOR,FIRST_TIMER,FIRST_TIME_CONTRIBUTOR,MANNEQUIN,MEMBER,NONE,OWNER
     */
    @Serializable
    enum class AuthorAssociation(val value: kotlin.String) {
        @SerialName(value = "COLLABORATOR") COLLABORATOR("COLLABORATOR"),
        @SerialName(value = "CONTRIBUTOR") CONTRIBUTOR("CONTRIBUTOR"),
        @SerialName(value = "FIRST_TIMER") FIRST_TIMER("FIRST_TIMER"),
        @SerialName(value = "FIRST_TIME_CONTRIBUTOR") FIRST_TIME_CONTRIBUTOR("FIRST_TIME_CONTRIBUTOR"),
        @SerialName(value = "MANNEQUIN") MANNEQUIN("MANNEQUIN"),
        @SerialName(value = "MEMBER") MEMBER("MEMBER"),
        @SerialName(value = "NONE") NONE("NONE"),
        @SerialName(value = "OWNER") OWNER("OWNER");
    }
}

