/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EnterpriseWebhooks
import org.openapitools.client.models.OrganizationSimpleWebhooks
import org.openapitools.client.models.RepositoryWebhooks
import org.openapitools.client.models.SimpleInstallation
import org.openapitools.client.models.SimpleUserWebhooks
import org.openapitools.client.models.WebhookProjectCardMovedChanges
import org.openapitools.client.models.WebhookProjectCardMovedProjectCard

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param action 
 * @param projectCard 
 * @param sender 
 * @param changes 
 * @param enterprise 
 * @param installation 
 * @param organization 
 * @param repository 
 */
@Serializable

data class WebhookProjectCardMoved (

    @SerialName(value = "action")
    val action: WebhookProjectCardMoved.Action,

    @SerialName(value = "project_card")
    val projectCard: WebhookProjectCardMovedProjectCard,

    @SerialName(value = "sender")
    val sender: SimpleUserWebhooks,

    @SerialName(value = "changes")
    val changes: WebhookProjectCardMovedChanges? = null,

    @SerialName(value = "enterprise")
    val enterprise: EnterpriseWebhooks? = null,

    @SerialName(value = "installation")
    val installation: SimpleInstallation? = null,

    @SerialName(value = "organization")
    val organization: OrganizationSimpleWebhooks? = null,

    @SerialName(value = "repository")
    val repository: RepositoryWebhooks? = null

) {

    /**
     * 
     *
     * Values: moved
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "moved") moved("moved");
    }
}

