/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SimpleCommit
import org.openapitools.client.models.SimpleCommitAuthor
import org.openapitools.client.models.SimpleCommitCommitter

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id SHA for the commit
 * @param treeId SHA for the commit's tree
 * @param message Message describing the purpose of the commit
 * @param timestamp Timestamp of the commit
 * @param author 
 * @param committer 
 */
@Serializable

data class WorkflowRunHeadCommit (

    /* SHA for the commit */
    @Contextual @SerialName(value = "id")
    val id: kotlin.Any?,

    /* SHA for the commit's tree */
    @Contextual @SerialName(value = "tree_id")
    val treeId: kotlin.Any?,

    /* Message describing the purpose of the commit */
    @Contextual @SerialName(value = "message")
    val message: kotlin.Any?,

    /* Timestamp of the commit */
    @Contextual @SerialName(value = "timestamp")
    val timestamp: kotlin.Any?,

    @SerialName(value = "author")
    val author: SimpleCommitAuthor,

    @SerialName(value = "committer")
    val committer: SimpleCommitCommitter

)

